# 학교알리미 학교폭력피해시간
- 데이터 
    - 학교알리미_2021_서울_학교폭력피해시간.csv(DataPreprocessing)
    - 학교알리미_2021_서울_시군구별_학교폭피해시간.csv(DataPreprocessing)

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/강남구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df2 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/강동구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df3 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/강북구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df4 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/강서구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df5 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/관악구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df6 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/광진구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df7 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/구로구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df8 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/금천구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df9 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/노원구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df10 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/도봉구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df11 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/동대문구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df12 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/동작구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df13 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/마포구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df14 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/서대문구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df15 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/서초구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df16 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/성동구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df17 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/성북구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df18 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/송파구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df19 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/양천구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df20 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/영등포구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df21 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/용산구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df22 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/은평구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df23 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/종로구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df24 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/중구_학교폭력_실태조사_피해시간(복수응답).xlsx")
df25 = pd.read_excel("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/Crawling/피해시간/중랑구_학교폭력_실태조사_피해시간(복수응답).xlsx")

In [3]:
da_time = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,
                           df11,df12,df13,df14,df15,df16,df17,df18,
                           df19,df20,df21,df22,df23,df24,df25], ignore_index=True)
da_time

,Unnamed: 0,구,학교명,구분,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,기타
0,0,강남구,개포고등학교,2021학년도,0,0,1,0,0,1,0,2,0
1,1,강남구,경기고등학교,2021학년도,1,1,2,2,1,1,1,0,0
2,2,강남구,경기여자고등학교,2021학년도,0,1,1,1,0,0,0,0,0
3,3,강남구,국립국악고등학교,2021학년도,0,0,0,0,0,0,0,0,0
4,4,강남구,단국대학교부속소프트웨어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,5,중랑구,원묵고등학교,2021학년도,0,0,0,0,0,0,0,0,0
316,6,중랑구,이화여자대학교병설미디어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
317,7,중랑구,중화고등학교,2021학년도,0,1,1,1,0,0,0,1,0
318,8,중랑구,태릉고등학교,2021학년도,0,0,0,0,0,0,0,0,1
319,9,중랑구,혜원여자고등학교,2021학년도,0,0,0,0,0,0,0,0,0

In [4]:
da_time.drop(['Unnamed: 0'], axis = 1,inplace=True)
da_time

,구,학교명,구분,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,기타
0,강남구,개포고등학교,2021학년도,0,0,1,0,0,1,0,2,0
1,강남구,경기고등학교,2021학년도,1,1,2,2,1,1,1,0,0
2,강남구,경기여자고등학교,2021학년도,0,1,1,1,0,0,0,0,0
3,강남구,국립국악고등학교,2021학년도,0,0,0,0,0,0,0,0,0
4,강남구,단국대학교부속소프트웨어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
315,중랑구,원묵고등학교,2021학년도,0,0,0,0,0,0,0,0,0
316,중랑구,이화여자대학교병설미디어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
317,중랑구,중화고등학교,2021학년도,0,1,1,1,0,0,0,1,0
318,중랑구,태릉고등학교,2021학년도,0,0,0,0,0,0,0,0,1
319,중랑구,혜원여자고등학교,2021학년도,0,0,0,0,0,0,0,0,0

In [5]:
da_time.rename(columns = {'구':'시군구'},inplace=True)
da_time

,시군구,학교명,구분,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,기타
0,강남구,개포고등학교,2021학년도,0,0,1,0,0,1,0,2,0
1,강남구,경기고등학교,2021학년도,1,1,2,2,1,1,1,0,0
2,강남구,경기여자고등학교,2021학년도,0,1,1,1,0,0,0,0,0
3,강남구,국립국악고등학교,2021학년도,0,0,0,0,0,0,0,0,0
4,강남구,단국대학교부속소프트웨어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
315,중랑구,원묵고등학교,2021학년도,0,0,0,0,0,0,0,0,0
316,중랑구,이화여자대학교병설미디어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
317,중랑구,중화고등학교,2021학년도,0,1,1,1,0,0,0,1,0
318,중랑구,태릉고등학교,2021학년도,0,0,0,0,0,0,0,0,1
319,중랑구,혜원여자고등학교,2021학년도,0,0,0,0,0,0,0,0,0

In [7]:
da_time.replace('은일정보산업고등학교', '유한공업고등학교',inplace=True)

In [8]:
# 저장 후 주석처리
da_time.to_csv("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/학교알리미_2021_서울_학교폭력피해시간.csv", index=False)

# 시군구 별 학교폭력피해시간

In [1]:
import pandas as pd
import numpy as np

In [2]:
da_time_df = pd.read_csv("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/학교알리미_2021_서울_학교폭력피해시간.csv")
da_time_df

,시군구,학교명,구분,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,기타
0,강남구,개포고등학교,2021학년도,0,0,1,0,0,1,0,2,0
1,강남구,경기고등학교,2021학년도,1,1,2,2,1,1,1,0,0
2,강남구,경기여자고등학교,2021학년도,0,1,1,1,0,0,0,0,0
3,강남구,국립국악고등학교,2021학년도,0,0,0,0,0,0,0,0,0
4,강남구,단국대학교부속소프트웨어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
315,중랑구,원묵고등학교,2021학년도,0,0,0,0,0,0,0,0,0
316,중랑구,이화여자대학교병설미디어고등학교,2021학년도,0,0,0,0,0,0,0,0,0
317,중랑구,중화고등학교,2021학년도,0,1,1,1,0,0,0,1,0
318,중랑구,태릉고등학교,2021학년도,0,0,0,0,0,0,0,0,1
319,중랑구,혜원여자고등학교,2021학년도,0,0,0,0,0,0,0,0,0

In [3]:
da_time_df = da_time_df.groupby(["시군구"]).agg({"등교시간":"sum","수업시간":"sum","쉬는시간":"sum","점심시간":"sum","학교 안방과후 시간":"sum",
                                          "하교시간":"sum","학교 밖체험활동 시간":"sum","학교 일과가끝난 후":"sum","기타":"sum"}).reset_index()
da_time_df

,시군구,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,기타
0,강남구,3,7,12,10,4,2,2,3,3
1,강동구,1,2,5,4,1,0,0,4,5
2,강북구,0,4,2,1,0,1,0,4,0
3,강서구,7,5,19,13,1,8,0,10,1
4,관악구,2,2,8,5,0,2,2,5,3
5,광진구,5,3,2,4,1,1,2,4,0
6,구로구,2,3,7,7,1,4,0,2,1
7,금천구,0,2,4,2,1,0,1,3,0
8,노원구,6,14,27,18,1,4,2,9,6
9,도봉구,3,2,4,2,0,1,0,2,0
10,동대문구,1,1,4,2,0,2,0,3,1
11,동작구,1,1,2,2,1,2,1,3,1
12,마포구,2,2,3,1,0,0,2,3,2
13,서대문구,1,0,5,3,0,1,1,2,0
14,서초구,1,1,3,4,1,2,1,6,3
15,성동구,1,4,6,4,0,3,0,0,2
16,성북구,2,1,3,1,0,1,1,2,5
17,송파구,1,3,5,3,1,3,1,6,3
18,양천구,0,4,13,6,1,3,0,7,3
19,영등포구,2,2,3,2,0,1,0,4,0
20,용산구,1,4,6,2,1,2,2,1,1
21,은평구,1,5,7,5,0,2,0,5,2
22,종로구,4,5,11,9,1,3,1,9,0
23,중구,0,2,2,3,0,0,0,3,1
24,중랑구,0,3,4,1,0,1,1,2,2

In [4]:
da_time_df.rename(columns = {'기타':'피해시간기타'},inplace=True)
da_time_df

,시군구,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,피해시간기타
0,강남구,3,7,12,10,4,2,2,3,3
1,강동구,1,2,5,4,1,0,0,4,5
2,강북구,0,4,2,1,0,1,0,4,0
3,강서구,7,5,19,13,1,8,0,10,1
4,관악구,2,2,8,5,0,2,2,5,3
5,광진구,5,3,2,4,1,1,2,4,0
6,구로구,2,3,7,7,1,4,0,2,1
7,금천구,0,2,4,2,1,0,1,3,0
8,노원구,6,14,27,18,1,4,2,9,6
9,도봉구,3,2,4,2,0,1,0,2,0
10,동대문구,1,1,4,2,0,2,0,3,1
11,동작구,1,1,2,2,1,2,1,3,1
12,마포구,2,2,3,1,0,0,2,3,2
13,서대문구,1,0,5,3,0,1,1,2,0
14,서초구,1,1,3,4,1,2,1,6,3
15,성동구,1,4,6,4,0,3,0,0,2
16,성북구,2,1,3,1,0,1,1,2,5
17,송파구,1,3,5,3,1,3,1,6,3
18,양천구,0,4,13,6,1,3,0,7,3
19,영등포구,2,2,3,2,0,1,0,4,0
20,용산구,1,4,6,2,1,2,2,1,1
21,은평구,1,5,7,5,0,2,0,5,2
22,종로구,4,5,11,9,1,3,1,9,0
23,중구,0,2,2,3,0,0,0,3,1
24,중랑구,0,3,4,1,0,1,1,2,2

In [5]:
da_time_df['피해시간합계']=da_time_df.sum(axis=1)
da_time_df

C:\Users\ppi06\AppData\Local\Temp\ipykernel_17436\3734390079.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  da_time_df['피해시간합계']=da_time_df.sum(axis=1)

,시군구,등교시간,수업시간,쉬는시간,점심시간,학교 안방과후 시간,하교시간,학교 밖체험활동 시간,학교 일과가끝난 후,피해시간기타,피해시간합계
0,강남구,3,7,12,10,4,2,2,3,3,46
1,강동구,1,2,5,4,1,0,0,4,5,22
2,강북구,0,4,2,1,0,1,0,4,0,12
3,강서구,7,5,19,13,1,8,0,10,1,64
4,관악구,2,2,8,5,0,2,2,5,3,29
5,광진구,5,3,2,4,1,1,2,4,0,22
6,구로구,2,3,7,7,1,4,0,2,1,27
7,금천구,0,2,4,2,1,0,1,3,0,13
8,노원구,6,14,27,18,1,4,2,9,6,87
9,도봉구,3,2,4,2,0,1,0,2,0,14
10,동대문구,1,1,4,2,0,2,0,3,1,14
11,동작구,1,1,2,2,1,2,1,3,1,14
12,마포구,2,2,3,1,0,0,2,3,2,15
13,서대문구,1,0,5,3,0,1,1,2,0,13
14,서초구,1,1,3,4,1,2,1,6,3,22
15,성동구,1,4,6,4,0,3,0,0,2,20
16,성북구,2,1,3,1,0,1,1,2,5,16
17,송파구,1,3,5,3,1,3,1,6,3,26
18,양천구,0,4,13,6,1,3,0,7,3,37
19,영등포구,2,2,3,2,0,1,0,4,0,14
20,용산구,1,4,6,2,1,2,2,1,1,20
21,은평구,1,5,7,5,0,2,0,5,2,27
22,종로구,4,5,11,9,1,3,1,9,0,43
23,중구,0,2,2,3,0,0,0,3,1,11
24,중랑구,0,3,4,1,0,1,1,2,2,14

In [6]:
# 저장 후 주석처리
# da_time_df.to_csv("C:/sooeun/DATAexam/ConvergenceProject-School_Violence/Data/학교알리미_2021_서울_시군구별_학교폭력피해시간.csv", index=False)