# 112 신고 영향요소 융합 데이터(스마트치안빅데이터플랫폼, 경찰청)

In [1]:
import pandas as pd
import numpy as np

In [2]:
# 데이터 불러오기 
data_headers = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_컬럼정의서_20230117.csv", encoding='cp949')

FileNotFoundError: [Errno 2] No such file or directory: 'D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_컬럼정의서_20230117.csv'

In [5]:
data_headers

    순서                    컬럼영문명      컬럼한글명    데이터타입   길이  PK여부  NOT NULL여부
0    1                  ACPT_YM       접수년월     CHAR    6     Y           N
1    2                 PLCST_NM       경찰서명  VARCHAR  255     Y           N
2    3         RPRT_CASCNT_WHOL     신고건수전체   NUMBER   30     N           Y
3    4            RPRT_SEX_MALE     신고성별남성   NUMBER   30     N           Y
4    5            RPRT_SEX_FMLE     신고성별여성   NUMBER   30     N           Y
5    6           RPRT_SEX_UNKWN     신고성별불상   NUMBER   30     N           Y
6    7             RPRT_SEX_ETC     신고성별기타   NUMBER   30     N           Y
7    8    ACPT_EMERG_TYPE_EMERG   접수긴급유형긴급   NUMBER   30     N           Y
8    9  ACPT_EMERG_TYPE_IMPRTNC   접수긴급유형중요   NUMBER   30     N           Y
9   10     ACPT_EMERG_TYPE_GNRL   접수긴급유형일반   NUMBER   30     N           Y
10  11    ACPT_EMERG_TYPE_CVAPP   접수긴급유형민원   NUMBER   30     N           Y
11  12      ACPT_EMERG_TYPE_ETC   접수긴급유형기타   NUMBER   30     N           Y
12  13              CFINC_DSTVC   사건종별가정폭력   NUMBER   30     N           Y
13  14               CFINC_DTVC  사건종별데이트폭력   NUMBER   30     N           Y
14  15               CFINC_MRDR     사건종별살인   NUMBER   30     N           Y
15  16              CFINC_SVLNC    사건종별성폭력   NUMBER   30     N           Y
16  17               CFINC_SUCD     사건종별자살   NUMBER   30     N           Y
17  18             CFINC_INCVLC     사건종별폭력   NUMBER   30     N           Y
18  19                CFINC_ETC     사건종별기타   NUMBER   30     N           Y
19  20           OCRN_DOTW_SNDD    발생요일일요일   NUMBER   30     N           Y
20  21            OCRN_DOTW_MON    발생요일월요일   NUMBER   30     N           Y
21  22            OCRN_DOTW_TUE    발생요일화요일   NUMBER   30     N           Y
22  23            OCRN_DOTW_WED    발생요일수요일   NUMBER   30     N           Y
23  24            OCRN_DOTW_THU    발생요일목요일   NUMBER   30     N           Y
24  25            OCRN_DOTW_FRI    발생요일금요일   NUMBER   30     N           Y
25  26            OCRN_DOTW_SAT    발생요일토요일   NUMBER   30     N           Y
26  27      MNTH_AVE_INCOME_AMT    월평균소득금액   NUMBER   30     N           Y
27  28       TOTL_RESID_PUL_CNT     총상주인구수   NUMBER   30     N           Y

In [6]:
# 112 신고 요소 불러오기
# index_col = 0 : 첫 번째 컬럼을 index로 사용하도록 지정하여 로드 
data_01 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210131_C_001.csv",header = None)
data_02 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210228_C_001.csv",header = None)
data_03 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210331_C_001.csv",header = None)
data_04 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210430_C_001.csv",header = None)
data_05 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210531_C_001.csv",header = None)
data_06 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210630_C_001.csv",header = None)
data_07 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210731_C_001.csv",header = None)
data_08 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210831_C_001.csv",header = None)
data_09 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20210930_C_001.csv",header = None)
data_10 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20211031_C_001.csv",header = None)
data_11 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20211130_C_001.csv",header = None)
data_12 = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/112_신고_영향요소/FSN_08_20211231_C_001.csv",header = None)

In [7]:
# 데이터 합치기
data = pd.concat([data_01, data_02, data_03, data_04, data_05, data_06, data_07,
                  data_08, data_09, data_10, data_11, data_12], axis=0)
data

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,202101,ETC,520268,171391,100200,242144,6533,491,12007,24063,...,517447,73026,69212,66571,69566,69276,88277,84340,0,0
1,202101,무주,186,87,48,51,0,0,46,93,...,178,36,27,20,24,24,22,33,0,0
2,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,6131,1078,838,795,946,731,1054,1177,3193595,523005
3,202101,진천,870,448,237,185,0,4,231,467,...,812,139,102,88,97,128,175,141,0,0
4,202101,삼척,960,500,296,164,0,5,159,443,...,889,137,116,129,123,89,180,186,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,202112,장성,434,237,91,106,0,5,135,221,...,421,42,66,49,61,75,80,61,0,0
270,202112,김해서부,2820,1482,733,605,0,63,491,1447,...,2596,296,378,324,507,416,498,401,0,0
271,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,8477,1094,1030,1093,1390,1410,1607,1445,4022976,978323
272,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,5345,664,732,750,966,928,985,719,2567770,231850
273,202112,포항북부,4177,2173,1184,820,0,4,687,2350,...,3963,486,530,534,597,698,744,588,0,0

In [22]:
# 컬럼명 변경 
data.columns = data_headers[' 컬럼한글명']
data

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,사건종별기타,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수
0,202101,ETC,520268,171391,100200,242144,6533,491,12007,24063,...,517447,73026,69212,66571,69566,69276,88277,84340,0,0
1,202101,무주,186,87,48,51,0,0,46,93,...,178,36,27,20,24,24,22,33,0,0
2,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,6131,1078,838,795,946,731,1054,1177,3193595,523005
3,202101,진천,870,448,237,185,0,4,231,467,...,812,139,102,88,97,128,175,141,0,0
4,202101,삼척,960,500,296,164,0,5,159,443,...,889,137,116,129,123,89,180,186,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,202112,장성,434,237,91,106,0,5,135,221,...,421,42,66,49,61,75,80,61,0,0
270,202112,김해서부,2820,1482,733,605,0,63,491,1447,...,2596,296,378,324,507,416,498,401,0,0
271,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,8477,1094,1030,1093,1390,1410,1607,1445,4022976,978323
272,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,5345,664,732,750,966,928,985,719,2567770,231850
273,202112,포항북부,4177,2173,1184,820,0,4,687,2350,...,3963,486,530,534,597,698,744,588,0,0

In [25]:
# 인덱스 재설정
data.reset_index(drop=True, inplace=True)
data

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,사건종별기타,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수
0,202101,ETC,520268,171391,100200,242144,6533,491,12007,24063,...,517447,73026,69212,66571,69566,69276,88277,84340,0,0
1,202101,무주,186,87,48,51,0,0,46,93,...,178,36,27,20,24,24,22,33,0,0
2,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,6131,1078,838,795,946,731,1054,1177,3193595,523005
3,202101,진천,870,448,237,185,0,4,231,467,...,812,139,102,88,97,128,175,141,0,0
4,202101,삼척,960,500,296,164,0,5,159,443,...,889,137,116,129,123,89,180,186,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3286,202112,장성,434,237,91,106,0,5,135,221,...,421,42,66,49,61,75,80,61,0,0
3287,202112,김해서부,2820,1482,733,605,0,63,491,1447,...,2596,296,378,324,507,416,498,401,0,0
3288,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,8477,1094,1030,1093,1390,1410,1607,1445,4022976,978323
3289,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,5345,664,732,750,966,928,985,719,2567770,231850
3290,202112,포항북부,4177,2173,1184,820,0,4,687,2350,...,3963,486,530,534,597,698,744,588,0,0

In [40]:
seoul_data = data[data['경찰서명'].str.contains('서울')]
seoul_data

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,사건종별기타,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수
2,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,6131,1078,838,795,946,731,1054,1177,3193595,523005
13,202101,서울양천,5560,2680,1870,1010,0,36,1229,2904,...,5196,819,670,751,670,697,1010,943,3563309,453832
29,202101,서울서부,2663,1298,855,510,0,17,653,1501,...,2457,423,312,289,345,392,427,475,3145893,292940
45,202101,서울광진,6207,3060,1821,1326,0,48,1531,3507,...,5720,992,758,781,786,763,993,1134,3066952,346546
51,202101,서울영등포,8986,4447,2863,1676,0,89,2074,4555,...,8437,1199,1110,1212,1298,1164,1505,1498,3548012,1103293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3257,202112,서울강서,10506,5398,3092,2016,0,135,2500,5760,...,9835,1204,1291,1258,1735,1656,1799,1563,3165221,1028629
3266,202112,서울청,674,358,211,105,0,76,416,152,...,589,78,76,82,114,106,100,118,0,0
3279,202112,서울중랑,7475,3826,2320,1329,0,106,1757,4124,...,6917,985,910,928,1187,1140,1280,1045,2560383,394574
3288,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,8477,1094,1030,1093,1390,1410,1607,1445,4022976,978323
3289,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,5345,664,732,750,966,928,985,719,2567770,231850

In [42]:
seoul_data.reset_index(drop=True, inplace=True)
seoul_data

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,사건종별기타,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수
0,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,6131,1078,838,795,946,731,1054,1177,3193595,523005
1,202101,서울양천,5560,2680,1870,1010,0,36,1229,2904,...,5196,819,670,751,670,697,1010,943,3563309,453832
2,202101,서울서부,2663,1298,855,510,0,17,653,1501,...,2457,423,312,289,345,392,427,475,3145893,292940
3,202101,서울광진,6207,3060,1821,1326,0,48,1531,3507,...,5720,992,758,781,786,763,993,1134,3066952,346546
4,202101,서울영등포,8986,4447,2863,1676,0,89,2074,4555,...,8437,1199,1110,1212,1298,1164,1505,1498,3548012,1103293
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,202112,서울강서,10506,5398,3092,2016,0,135,2500,5760,...,9835,1204,1291,1258,1735,1656,1799,1563,3165221,1028629
380,202112,서울청,674,358,211,105,0,76,416,152,...,589,78,76,82,114,106,100,118,0,0
381,202112,서울중랑,7475,3826,2320,1329,0,106,1757,4124,...,6917,985,910,928,1187,1140,1280,1045,2560383,394574
382,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,8477,1094,1030,1093,1390,1410,1607,1445,4022976,978323
383,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,5345,664,732,750,966,928,985,719,2567770,231850

In [50]:
# 경찰서명 서울 자르고 시군구 열 추가하기 
seoul_data["시군구"]=seoul_data["경찰서명"].str[2:5]
seoul_data

C:\Users\sunfo\AppData\Local\Temp\ipykernel_8228\2537824503.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_data["시군구"]=seoul_data["경찰서명"].str[2:5]

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수,시군구
0,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,1078,838,795,946,731,1054,1177,3193595,523005,노원
1,202101,서울양천,5560,2680,1870,1010,0,36,1229,2904,...,819,670,751,670,697,1010,943,3563309,453832,양천
2,202101,서울서부,2663,1298,855,510,0,17,653,1501,...,423,312,289,345,392,427,475,3145893,292940,서부
3,202101,서울광진,6207,3060,1821,1326,0,48,1531,3507,...,992,758,781,786,763,993,1134,3066952,346546,광진
4,202101,서울영등포,8986,4447,2863,1676,0,89,2074,4555,...,1199,1110,1212,1298,1164,1505,1498,3548012,1103293,영등포
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,202112,서울강서,10506,5398,3092,2016,0,135,2500,5760,...,1204,1291,1258,1735,1656,1799,1563,3165221,1028629,강서
380,202112,서울청,674,358,211,105,0,76,416,152,...,78,76,82,114,106,100,118,0,0,청
381,202112,서울중랑,7475,3826,2320,1329,0,106,1757,4124,...,985,910,928,1187,1140,1280,1045,2560383,394574,중랑
382,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,1094,1030,1093,1390,1410,1607,1445,4022976,978323,마포
383,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,664,732,750,966,928,985,719,2567770,231850,금천

In [52]:
# 시군구 수정하기 1 - 구 붙이기 
seoul_data['시군구'] = seoul_data['시군구'] + "구"
seoul_data

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수,시군구
0,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,1078,838,795,946,731,1054,1177,3193595,523005,노원구
1,202101,서울양천,5560,2680,1870,1010,0,36,1229,2904,...,819,670,751,670,697,1010,943,3563309,453832,양천구
2,202101,서울서부,2663,1298,855,510,0,17,653,1501,...,423,312,289,345,392,427,475,3145893,292940,서부구
3,202101,서울광진,6207,3060,1821,1326,0,48,1531,3507,...,992,758,781,786,763,993,1134,3066952,346546,광진구
4,202101,서울영등포,8986,4447,2863,1676,0,89,2074,4555,...,1199,1110,1212,1298,1164,1505,1498,3548012,1103293,영등포구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,202112,서울강서,10506,5398,3092,2016,0,135,2500,5760,...,1204,1291,1258,1735,1656,1799,1563,3165221,1028629,강서구
380,202112,서울청,674,358,211,105,0,76,416,152,...,78,76,82,114,106,100,118,0,0,청구
381,202112,서울중랑,7475,3826,2320,1329,0,106,1757,4124,...,985,910,928,1187,1140,1280,1045,2560383,394574,중랑구
382,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,1094,1030,1093,1390,1410,1607,1445,4022976,978323,마포구
383,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,664,732,750,966,928,985,719,2567770,231850,금천구

In [54]:
 # 시군구 수정하기1 - 경찰청 시군구 위치로 시군구 매핑 
seoul_data = seoul_data.replace({'시군구' : '수서구'}, '강남구')
seoul_data = seoul_data.replace({'시군구' : '중부구'}, '중구')
seoul_data = seoul_data.replace({'시군구' : '종암구'}, '성북구')
seoul_data = seoul_data.replace({'시군구' : '서부구'}, '은평구')
seoul_data = seoul_data.replace({'시군구' : '방배구'}, '서초구')
seoul_data = seoul_data.replace({'시군구' : '혜화구'}, '종로구')
seoul_data = seoul_data.replace({'시군구' : '남대문구'}, '중구')
seoul_data = seoul_data.replace({'시군구' : '청구'}, '종로구')
seoul_data

컬럼한글명,접수년월,경찰서명,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,...,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수,시군구
0,202101,서울노원,6619,3312,1901,1406,0,71,1739,3502,...,1078,838,795,946,731,1054,1177,3193595,523005,노원구
1,202101,서울양천,5560,2680,1870,1010,0,36,1229,2904,...,819,670,751,670,697,1010,943,3563309,453832,양천구
2,202101,서울서부,2663,1298,855,510,0,17,653,1501,...,423,312,289,345,392,427,475,3145893,292940,은평구
3,202101,서울광진,6207,3060,1821,1326,0,48,1531,3507,...,992,758,781,786,763,993,1134,3066952,346546,광진구
4,202101,서울영등포,8986,4447,2863,1676,0,89,2074,4555,...,1199,1110,1212,1298,1164,1505,1498,3548012,1103293,영등포구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
379,202112,서울강서,10506,5398,3092,2016,0,135,2500,5760,...,1204,1291,1258,1735,1656,1799,1563,3165221,1028629,강서구
380,202112,서울청,674,358,211,105,0,76,416,152,...,78,76,82,114,106,100,118,0,0,종로구
381,202112,서울중랑,7475,3826,2320,1329,0,106,1757,4124,...,985,910,928,1187,1140,1280,1045,2560383,394574,중랑구
382,202112,서울마포,9069,4728,2494,1847,0,192,2259,4985,...,1094,1030,1093,1390,1410,1607,1445,4022976,978323,마포구
383,202112,서울금천,5744,3139,1571,1034,0,91,1431,3105,...,664,732,750,966,928,985,719,2567770,231850,금천구

In [59]:
seoul_data.groupby('시군구').sum().columns

Index(['접수년월', '신고건수전체', '신고성별남성', '신고성별여성', '신고성별불상', '신고성별기타', '접수긴급유형긴급',
       '접수긴급유형중요', '접수긴급유형일반', '접수긴급유형민원', '접수긴급유형기타', '사건종별가정폭력', '사건종별데이트폭력',
       '사건종별살인', '사건종별성폭력', '사건종별자살', '사건종별폭력', '사건종별기타', '발생요일일요일', '발생요일월요일',
       '발생요일화요일', '발생요일수요일', '발생요일목요일', '발생요일금요일', '발생요일토요일', '월평균소득금액',
       '총상주인구수'],
      dtype='object', name=' 컬럼한글명')

In [66]:
# 구별 평균 계산
seoul_data_fin = seoul_data.groupby('시군구').mean()
seoul_data_fin

컬럼한글명,접수년월,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,접수긴급유형민원,...,사건종별기타,발생요일일요일,발생요일월요일,발생요일화요일,발생요일수요일,발생요일목요일,발생요일금요일,발생요일토요일,월평균소득금액,총상주인구수
시군구,,,,,,,,,,,,,,,,,,,,,
강남구,202106.5,8916.875000,4521.875000,2339.541667,2055.458333,0.000000,80.208333,1721.541667,5093.500000,970.166667,...,8456.625000,990.541667,1173.625000,1293.041667,1346.666667,1356.750000,1465.500000,1290.750000,4.799007e+06,384267.0
강동구,202106.5,8031.166667,4080.666667,2207.583333,1742.833333,0.083333,75.083333,1759.000000,4560.166667,707.666667,...,7472.583333,1088.166667,1100.000000,1103.500000,1107.833333,1135.666667,1209.833333,1286.166667,3.336210e+06,494875.0
강북구,202106.5,6647.083333,3390.250000,2005.583333,1251.250000,0.000000,41.000000,1440.666667,3854.416667,550.416667,...,6158.833333,946.250000,888.666667,875.000000,922.833333,924.333333,1024.333333,1065.666667,2.599556e+06,209798.0
강서구,202106.5,10781.833333,5477.416667,3094.083333,2210.333333,0.000000,71.416667,2269.916667,6008.083333,1085.166667,...,10061.666667,1437.666667,1438.583333,1447.666667,1526.666667,1548.416667,1689.000000,1693.833333,3.165221e+06,1028629.0
관악구,202106.5,9557.333333,4853.583333,2620.833333,2082.916667,0.000000,66.666667,2036.750000,5432.833333,1006.083333,...,8880.250000,1346.666667,1275.750000,1272.583333,1320.250000,1354.083333,1440.583333,1547.416667,2.782525e+06,494375.0
광진구,202106.5,7545.750000,3761.916667,2179.083333,1604.750000,0.000000,70.666667,1631.583333,4364.500000,703.833333,...,7032.416667,1065.416667,1002.583333,982.583333,1074.166667,1050.333333,1156.500000,1214.166667,3.066952e+06,346546.0
구로구,202106.5,7997.166667,4140.416667,2315.083333,1541.666667,0.000000,59.833333,1668.416667,4411.916667,784.083333,...,7450.166667,1079.833333,1088.333333,1076.250000,1124.250000,1119.833333,1292.666667,1216.000000,2.890323e+06,478336.0
금천구,202106.5,5956.000000,3205.916667,1656.250000,1093.833333,0.000000,50.416667,1312.583333,3316.666667,570.666667,...,5519.750000,755.416667,805.666667,839.000000,852.166667,850.583333,957.666667,895.500000,2.567770e+06,231850.0
노원구,202106.5,8158.916667,4118.916667,2286.666667,1753.333333,0.000000,64.750000,1826.583333,4520.333333,788.500000,...,7606.666667,1127.750000,1106.750000,1103.500000,1148.166667,1127.250000,1234.583333,1310.916667,3.193595e+06,523005.0
도봉구,202106.5,4994.416667,2535.000000,1491.000000,968.416667,0.000000,35.333333,1107.166667,2901.333333,467.666667,...,4594.666667,728.250000,683.416667,659.583333,680.083333,685.250000,743.666667,814.166667,2.713315e+06,325263.0
동대문구,202106.5,7712.083333,4094.750000,2168.583333,1448.750000,0.000000,45.666667,1590.083333,4546.333333,647.166667,...,7216.166667,1022.583333,1064.333333,1058.083333,1087.083333,1095.833333,1176.000000,1208.166667,3.011303e+06,373552.0
동작구,202106.5,6399.000000,3255.416667,1853.416667,1290.166667,0.000000,52.000000,1413.250000,3530.750000,671.916667,...,6012.166667,819.000000,864.833333,900.250000,914.083333,922.833333,997.916667,980.083333,3.436506e+06,495828.0
마포구,202106.5,9544.500000,4939.333333,2533.583333,2071.583333,0.000000,100.083333,2082.916667,5492.250000,991.000000,...,8977.500000,1353.666667,1191.333333,1222.750000,1274.666667,1312.083333,1511.416667,1678.583333,4.022976e+06,978323.0
서대문구,202106.5,6067.916667,2903.416667,1707.250000,1457.166667,0.083333,41.750000,1180.000000,3312.666667,634.416667,...,5753.916667,774.833333,843.000000,833.833333,851.000000,869.416667,958.333333,937.500000,3.943923e+06,511110.0
서초구,202106.5,5167.708333,2604.458333,1392.458333,1170.750000,0.041667,47.166667,1053.833333,2838.541667,512.416667,...,4919.416667,561.583333,683.916667,748.375000,771.625000,790.250000,843.875000,768.083333,4.657076e+06,279720.5
성동구,202106.5,5673.000000,3085.250000,1462.166667,1125.583333,0.000000,43.666667,1251.083333,3314.916667,503.000000,...,5372.083333,715.750000,745.500000,769.833333,826.416667,842.750000,907.250000,865.500000,3.535332e+06,394954.0
성북구,202106.5,3414.125000,1755.500000,993.083333,665.541667,0.000000,28.208333,772.041667,1927.375000,328.125000,...,3184.250000,456.875000,464.166667,469.916667,474.416667,482.041667,532.208333,534.500000,3.181782e+06,524983.5
송파구,202106.5,11608.583333,5941.666667,3279.000000,2387.916667,0.000000,89.250000,2517.583333,6600.250000,1201.333333,...,10906.833333,1445.583333,1561.916667,1642.500000,1664.833333,1696.083333,1809.083333,1788.583333,3.969562e+06,758474.0
양천구,202106.5,7344.500000,3497.916667,2447.916667,1398.666667,0.000000,49.666667,1456.750000,3845.750000,699.500000,...,6937.666667,957.000000,1013.500000,1039.666667,1025.333333,1032.250000,1137.666667,1139.083333,3.563309e+06,453832.0
영등포구,202106.5,11047.500000,5727.916667,3080.916667,2238.666667,0.000000,92.166667,2243.500000,5875.666667,1141.333333,...,10410.250000,1443.250000,1480.500000,1525.750000,1559.916667,1615.500000,1714.583333,1708.000000,3.548012e+06,1103293.0
용산구,202106.5,6080.833333,3026.250000,1558.166667,1496.416667,0.000000,50.666667,1208.083333,3381.083333,553.250000,...,5735.666667,879.000000,800.083333,791.333333,827.666667,827.750000,920.000000,1035.000000,3.783427e+06,558137.0
은평구,202106.5,3805.000000,1887.666667,1183.541667,733.791667,0.000000,23.541667,778.750000,2254.833333,362.333333,...,3545.833333,525.250000,511.416667,515.916667,524.916667,533.875000,580.041667,613.583333,2.984036e+06,288348.5
종로구,202106.5,2427.388889,1331.722222,624.388889,471.277778,0.000000,27.194444,542.250000,1382.833333,223.333333,...,2277.666667,306.583333,320.861111,331.000000,349.833333,354.500000,384.472222,380.138889,2.305023e+06,273631.0
중구,202106.5,3105.166667,1688.500000,774.625000,642.041667,0.000000,19.875000,597.125000,1852.791667,295.875000,...,2923.958333,361.041667,418.041667,450.916667,459.666667,464.875000,498.833333,451.791667,3.910224e+06,191910.0
중랑구,202106.5,8354.500000,4132.833333,2567.250000,1654.416667,0.000000,56.166667,1723.250000,4616.333333,667.333333,...,7745.333333,1208.583333,1141.500000,1099.083333,1161.083333,1140.750000,1270.833333,1332.666667,2.560383e+06,394574.0

In [67]:
seoul_data_fin.columns

Index(['접수년월', '신고건수전체', '신고성별남성', '신고성별여성', '신고성별불상', '신고성별기타', '접수긴급유형긴급',
       '접수긴급유형중요', '접수긴급유형일반', '접수긴급유형민원', '접수긴급유형기타', '사건종별가정폭력', '사건종별데이트폭력',
       '사건종별살인', '사건종별성폭력', '사건종별자살', '사건종별폭력', '사건종별기타', '발생요일일요일', '발생요일월요일',
       '발생요일화요일', '발생요일수요일', '발생요일목요일', '발생요일금요일', '발생요일토요일', '월평균소득금액',
       '총상주인구수'],
      dtype='object', name=' 컬럼한글명')

In [69]:
# 지수표현 방지
pd.options.display.float_format = '{:.5f}'.format

In [71]:
seoul_data_fin = seoul_data_fin[['신고건수전체', '사건종별가정폭력', '사건종별데이트폭력', '월평균소득금액', '총상주인구수']]
seoul_data_fin

 컬럼한글명      신고건수전체  사건종별가정폭력  사건종별데이트폭력       월평균소득금액        총상주인구수
시군구
강남구     8916.87500  87.12500   62.41667 4799007.00000  384267.00000
강동구     8031.16667 151.16667   35.91667 3336210.00000  494875.00000
강북구     6647.08333 117.50000   33.75000 2599556.00000  209798.00000
강서구    10781.83333 198.75000   61.50000 3165221.00000 1028629.00000
관악구     9557.33333 134.16667   57.41667 2782525.00000  494375.00000
광진구     7545.75000 109.50000   32.58333 3066952.00000  346546.00000
구로구     7997.16667 136.50000   22.33333 2890323.00000  478336.00000
금천구     5956.00000 118.58333   26.66667 2567770.00000  231850.00000
노원구     8158.91667 197.08333   25.58333 3193595.00000  523005.00000
도봉구     4994.41667 141.33333   26.83333 2713315.00000  325263.00000
동대문구    7712.08333 107.58333   32.00000 3011303.00000  373552.00000
동작구     6399.00000  94.58333   18.83333 3436506.00000  495828.00000
마포구     9544.50000 106.16667   34.41667 4022976.00000  978323.00000
서대문구    6067.91667  80.41667   15.91667 3943923.00000  511110.00000
서초구     5167.70833  63.08333   15.00000 4657075.50000  279720.50000
성동구     5673.00000  61.33333   17.08333 3535332.00000  394954.00000
성북구     3414.12500  69.70833   10.41667 3181781.50000  524983.50000
송파구    11608.58333 204.75000   44.75000 3969562.00000  758474.00000
양천구     7344.50000 133.00000   18.58333 3563309.00000  453832.00000
영등포구   11047.50000  98.00000   25.58333 3548012.00000 1103293.00000
용산구     6080.83333  50.50000   21.75000 3783427.00000  558137.00000
은평구     3805.00000  78.79167   13.62500 2984035.50000  288348.50000
종로구     2427.38889  11.97222    4.94444 2305023.33333  273631.00000
중구      3105.16667  21.33333    7.08333 3910223.50000  191910.00000
중랑구     8354.50000 173.25000   47.66667 2560383.00000  394574.00000

In [79]:
school_violence = pd.read_csv("D:/MultiCampus/DATAexam/융복합/폭력분석/data/경찰청_2021_서울_시군구처리_학교폭력데이터.csv")
school_violence

,Unnamed: 0,시군구,접수년도,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
0,0,강남구,2021,40,15,17,8,0,2,21,...,2,8,1,2,2,3,2,4,1,0
1,1,강동구,2021,61,30,25,6,0,0,40,...,6,4,6,4,10,3,3,2,8,1
2,2,강북구,2021,43,25,15,3,0,0,26,...,1,3,6,3,9,7,1,4,2,4
3,3,강서구,2021,79,26,47,6,0,1,39,...,4,4,6,5,9,10,5,9,11,3
4,4,관악구,2021,51,26,18,7,0,0,28,...,3,6,4,7,5,0,6,3,3,4
5,5,광진구,2021,48,18,25,5,0,1,27,...,7,4,6,5,4,3,0,8,1,2
6,6,구로구,2021,39,21,17,1,0,1,21,...,4,2,2,3,6,1,1,3,4,2
7,7,금천구,2021,28,16,8,4,0,0,14,...,3,3,2,2,2,3,1,1,3,0
8,8,노원구,2021,71,35,23,13,0,0,36,...,7,9,5,6,6,8,3,4,6,0
9,9,도봉구,2021,53,22,24,7,0,0,26,...,7,4,7,4,4,5,6,3,4,0
10,10,동대문구,2021,46,27,15,4,0,1,30,...,5,5,0,8,5,3,3,1,3,5
11,11,동작구,2021,25,13,11,1,0,0,15,...,4,2,3,3,3,1,1,3,0,1
12,12,마포구,2021,42,24,13,5,0,2,16,...,3,0,7,3,2,1,4,2,2,4
13,13,서대문구,2021,29,11,10,8,0,0,19,...,1,4,2,4,3,4,1,2,1,3
14,14,서초구,2021,25,12,6,7,0,0,12,...,3,5,6,0,1,0,1,1,1,2
15,15,성동구,2021,22,9,13,0,0,0,11,...,1,3,1,4,2,3,1,1,1,0
16,16,성북구,2021,39,21,15,3,0,1,26,...,0,1,3,1,2,6,3,2,5,2
17,17,송파구,2021,72,32,30,10,0,1,44,...,2,2,10,8,6,8,2,6,6,0
18,18,양천구,2021,69,33,32,4,0,0,37,...,3,6,5,6,5,10,4,2,4,6
19,19,영등포구,2021,39,19,16,4,0,0,22,...,2,1,1,8,7,3,2,2,2,3
20,20,용산구,2021,14,5,3,6,0,0,6,...,2,1,0,1,1,1,3,1,1,0
21,21,은평구,2021,69,24,29,16,0,0,43,...,6,6,12,6,11,6,3,7,2,3
22,22,종로구,2021,8,3,4,1,0,0,6,...,2,1,1,0,1,0,0,0,1,0
23,23,중구,2021,17,6,9,2,0,2,9,...,5,2,1,1,0,0,2,0,1,0
24,24,중랑구,2021,73,34,28,11,0,3,48,...,4,6,6,12,11,5,9,3,2,4

In [80]:
school_violence.drop('Unnamed: 0', axis=1, inplace=True)
school_violence.index = school_violence['시군구']
school_violence.drop('시군구', axis=1, inplace=True)
school_violence

,접수년도,신고건수전체,신고성별남성,신고성별여성,신고성별불상,신고성별기타,접수긴급유형긴급,접수긴급유형중요,접수긴급유형일반,접수긴급유형민원,...,발생시간대14,발생시간대15,발생시간대16,발생시간대17,발생시간대18,발생시간대19,발생시간대20,발생시간대21,발생시간대22,발생시간대23
시군구,,,,,,,,,,,,,,,,,,,,,
강남구,2021,40,15,17,8,0,2,21,16,1,...,2,8,1,2,2,3,2,4,1,0
강동구,2021,61,30,25,6,0,0,40,18,3,...,6,4,6,4,10,3,3,2,8,1
강북구,2021,43,25,15,3,0,0,26,17,0,...,1,3,6,3,9,7,1,4,2,4
강서구,2021,79,26,47,6,0,1,39,36,3,...,4,4,6,5,9,10,5,9,11,3
관악구,2021,51,26,18,7,0,0,28,14,9,...,3,6,4,7,5,0,6,3,3,4
광진구,2021,48,18,25,5,0,1,27,17,3,...,7,4,6,5,4,3,0,8,1,2
구로구,2021,39,21,17,1,0,1,21,16,1,...,4,2,2,3,6,1,1,3,4,2
금천구,2021,28,16,8,4,0,0,14,12,2,...,3,3,2,2,2,3,1,1,3,0
노원구,2021,71,35,23,13,0,0,36,28,6,...,7,9,5,6,6,8,3,4,6,0
도봉구,2021,53,22,24,7,0,0,26,22,3,...,7,4,7,4,4,5,6,3,4,0
동대문구,2021,46,27,15,4,0,1,30,10,4,...,5,5,0,8,5,3,3,1,3,5
동작구,2021,25,13,11,1,0,0,15,9,1,...,4,2,3,3,3,1,1,3,0,1
마포구,2021,42,24,13,5,0,2,16,21,2,...,3,0,7,3,2,1,4,2,2,4
서대문구,2021,29,11,10,8,0,0,19,8,2,...,1,4,2,4,3,4,1,2,1,3
서초구,2021,25,12,6,7,0,0,12,12,1,...,3,5,6,0,1,0,1,1,1,2
성동구,2021,22,9,13,0,0,0,11,10,1,...,1,3,1,4,2,3,1,1,1,0
성북구,2021,39,21,15,3,0,1,26,10,1,...,0,1,3,1,2,6,3,2,5,2
송파구,2021,72,32,30,10,0,1,44,23,3,...,2,2,10,8,6,8,2,6,6,0
양천구,2021,69,33,32,4,0,0,37,28,4,...,3,6,5,6,5,10,4,2,4,6
영등포구,2021,39,19,16,4,0,0,22,14,3,...,2,1,1,8,7,3,2,2,2,3
용산구,2021,14,5,3,6,0,0,6,6,2,...,2,1,0,1,1,1,3,1,1,0
은평구,2021,69,24,29,16,0,0,43,20,5,...,6,6,12,6,11,6,3,7,2,3
종로구,2021,8,3,4,1,0,0,6,2,0,...,2,1,1,0,1,0,0,0,1,0
중구,2021,17,6,9,2,0,2,9,5,1,...,5,2,1,1,0,0,2,0,1,0
중랑구,2021,73,34,28,11,0,3,48,22,0,...,4,6,6,12,11,5,9,3,2,4

In [81]:
seoul_data_fin['학교폭력 신고 수'] = school_violence['신고건수전체']
seoul_data_fin

C:\Users\sunfo\AppData\Local\Temp\ipykernel_8228\1853743455.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  seoul_data_fin['학교폭력 신고 수'] = school_violence['신고건수전체']

 컬럼한글명      신고건수전체  사건종별가정폭력  사건종별데이트폭력       월평균소득금액        총상주인구수  학교폭력 신고 수
시군구
강남구     8916.87500  87.12500   62.41667 4799007.00000  384267.00000         40
강동구     8031.16667 151.16667   35.91667 3336210.00000  494875.00000         61
강북구     6647.08333 117.50000   33.75000 2599556.00000  209798.00000         43
강서구    10781.83333 198.75000   61.50000 3165221.00000 1028629.00000         79
관악구     9557.33333 134.16667   57.41667 2782525.00000  494375.00000         51
광진구     7545.75000 109.50000   32.58333 3066952.00000  346546.00000         48
구로구     7997.16667 136.50000   22.33333 2890323.00000  478336.00000         39
금천구     5956.00000 118.58333   26.66667 2567770.00000  231850.00000         28
노원구     8158.91667 197.08333   25.58333 3193595.00000  523005.00000         71
도봉구     4994.41667 141.33333   26.83333 2713315.00000  325263.00000         53
동대문구    7712.08333 107.58333   32.00000 3011303.00000  373552.00000         46
동작구     6399.00000  94.58333   18.83333 3436506.00000  495828.00000         25
마포구     9544.50000 106.16667   34.41667 4022976.00000  978323.00000         42
서대문구    6067.91667  80.41667   15.91667 3943923.00000  511110.00000         29
서초구     5167.70833  63.08333   15.00000 4657075.50000  279720.50000         25
성동구     5673.00000  61.33333   17.08333 3535332.00000  394954.00000         22
성북구     3414.12500  69.70833   10.41667 3181781.50000  524983.50000         39
송파구    11608.58333 204.75000   44.75000 3969562.00000  758474.00000         72
양천구     7344.50000 133.00000   18.58333 3563309.00000  453832.00000         69
영등포구   11047.50000  98.00000   25.58333 3548012.00000 1103293.00000         39
용산구     6080.83333  50.50000   21.75000 3783427.00000  558137.00000         14
은평구     3805.00000  78.79167   13.62500 2984035.50000  288348.50000         69
종로구     2427.38889  11.97222    4.94444 2305023.33333  273631.00000          8
중구      3105.16667  21.33333    7.08333 3910223.50000  191910.00000         17
중랑구     8354.50000 173.25000   47.66667 2560383.00000  394574.00000         73

In [82]:
seoul_data_fin.corr()

 컬럼한글명     신고건수전체  사건종별가정폭력  사건종별데이트폭력  월평균소득금액  총상주인구수  학교폭력 신고 수
 컬럼한글명
신고건수전체    1.00000   0.72414    0.77571  0.18543 0.71205    0.55080
사건종별가정폭력  0.72414   1.00000    0.64570 -0.19823 0.38331    0.85233
사건종별데이트폭력 0.77571   0.64570    1.00000  0.05007 0.35584    0.55067
월평균소득금액   0.18543  -0.19823    0.05007  1.00000 0.23914   -0.17047
총상주인구수    0.71205   0.38331    0.35584  0.23914 1.00000    0.30451
학교폭력 신고 수 0.55080   0.85233    0.55067 -0.17047 0.30451    1.00000

In [86]:
seoul_data_fin.to_csv('D:/MultiCampus/DATAexam/융복합/폭력분석/data/서울_시군구_112신고영향요소_학교폭력신고수.csv', encoding='utf-8-sig')