In [5]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings(action='ignore')

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from scipy.spatial.distance import cdist, pdist
from sklearn.preprocessing import StandardScaler
from haversine import haversine
from tqdm import tqdm

In [6]:
school_loc_data= pd.read_csv("/Users/hyeoxx/Downloads/나이스_서울_전체_위경도_학교기본정보_Ver2.csv")
school_loc_data

,Unnamed: 0,시도교육청코드,시도교육청명,표준학교코드,학교명,영문학교명,학교종류명,소재지명,시군구,관할조직명,...,산업체특별학급존재여부,고등학교일반실업구분명,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,수정일,위도,경도
0,0,B10,서울특별시교육청,7010057,가락고등학교,Garak High School,고등학교,서울특별시,송파구,서울특별시교육청,...,N,일반계,NaN,후기,주간,19881223,19890428,20230115,37.501076,127.116426
1,1,B10,서울특별시교육청,7011169,가재울고등학교,Gajaeul High School,고등학교,서울특별시,서대문구,서울특별시교육청,...,N,일반계,NaN,후기,주간,20130301,20130501,20230115,37.574364,126.909530
2,2,B10,서울특별시교육청,7010117,강동고등학교,Kangdong High School,고등학교,서울특별시,강동구,서울특별시교육청,...,N,일반계,NaN,후기,주간,19841217,19850908,20230115,37.549917,127.160668
3,3,B10,서울특별시교육청,7010118,강서고등학교,Gangseo High School,고등학교,서울특별시,양천구,서울특별시교육청,...,N,일반계,NaN,후기,주간,19831101,19831101,20230115,37.536316,126.865771
4,4,B10,서울특별시교육청,7010270,강서공업고등학교,Gangseo Technical High School,고등학교,서울특별시,강서구,서울특별시교육청,...,N,전문계,NaN,전기,주간,19940105,19940105,20230115,37.576034,126.816182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,315,B10,서울특별시교육청,7010766,효문고등학교,Hyomun High School,고등학교,서울특별시,도봉구,서울특별시교육청,...,N,일반계,NaN,후기,주간,20051229,20060605,20230115,37.652699,127.018400
316,316,B10,서울특별시교육청,7010292,휘경공업고등학교,Hwigyeong Technical High School,고등학교,서울특별시,동대문구,서울특별시교육청,...,N,전문계,NaN,전기,주간,19971220,19980702,20230115,37.585153,127.069451
317,317,B10,서울특별시교육청,7010267,휘경여자고등학교,Hwikyung Girls` High School,고등학교,서울특별시,동대문구,서울특별시교육청,...,N,일반계,NaN,후기,주간,19750303,19750519,20230115,37.581901,127.067434
318,318,B10,서울특별시교육청,7010268,휘문고등학교,Whimoon High School,고등학교,서울특별시,강남구,서울특별시교육청,...,N,일반계,NaN,전기,주간,19060501,19060501,20230115,37.505289,127.061994
319,319,B10,서울특별시교육청,7011113,휘봉고등학교,HWIBONG High School,고등학교,서울특별시,동대문구,서울특별시교육청,...,N,일반계,NaN,후기,주간,20120106,20120501,20230115,37.586372,127.068941

In [7]:
Harmful_loc_data = pd.read_csv("/Users/hyeoxx/Desktop/혁준/shj/DATAexam/융복합/청소년유해업소.csv")
Harmful_loc_data

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,시군구명,법정동명,경도,위도
0,디라운지,관광/여가/오락,무도/유흥/가무,나이트클럽,강남구,신사동,127.033094,37.527180
1,제이에스무인호텔,숙박,모텔/여관/여인숙,모텔/여관/여인숙,강남구,삼성동,127.051437,37.506415
2,유림장여관,숙박,모텔/여관/여인숙,모텔/여관/여인숙,강남구,삼성동,127.049645,37.513051
3,명성모텔,숙박,모텔/여관/여인숙,모텔/여관/여인숙,강남구,역삼동,127.043979,37.504076
4,코메디클럽,관광/여가/오락,무도/유흥/가무,나이트클럽,강남구,논현동,127.037765,37.508855
...,...,...,...,...,...,...,...,...
1545,운호여관,숙박,모텔/여관/여인숙,모텔/여관/여인숙,중랑구,상봉동,127.090883,37.595335
1546,봉산여인숙,숙박,모텔/여관/여인숙,모텔/여관/여인숙,중랑구,망우동,127.093488,37.598112
1547,희망모텔,숙박,모텔/여관/여인숙,모텔/여관/여인숙,중랑구,중화동,127.079759,37.598384
1548,에덴장,숙박,모텔/여관/여인숙,모텔/여관/여인숙,중랑구,상봉동,127.089806,37.595462
1549,마니아,소매,기타판매업,성인용품판매,중랑구,망우동,127.101010,37.599774

In [8]:
# 유해업소수 구하는 함수 
def close_Harmful(school_loc_data, Harmful_loc_data): 
    schoolloc, Harmfulloc, Harmful_cnt = [], [], []
    for col in tqdm(school_loc_data.itertuples()): 
        schoolloc = [col.위도, col.경도]
        distance = []
        for col2 in Harmful_loc_data.itertuples(): 
            Harmfulloc = [col2.위도, col2.경도]
            distance.append(haversine(schoolloc, Harmfulloc, unit = 'm'))
            
        distance = [d for d in distance if d <= 500] 
        Harmful_cnt.append(len(distance))
    return Harmful_cnt

In [9]:
# school_loc_data = close_Harmful(school_loc_data, police_loc_data, "500미터내_파출소개수")
school_loc_data['500m_inner_Harmful_dept'] = close_Harmful(school_loc_data, Harmful_loc_data)
school_loc_data

320it [00:02, 149.27it/s]

,Unnamed: 0,시도교육청코드,시도교육청명,표준학교코드,학교명,영문학교명,학교종류명,소재지명,시군구,관할조직명,...,고등학교일반실업구분명,특수목적고등학교계열명,입시전후기구분명,주야구분명,설립일자,개교기념일,수정일,위도,경도,500m_inner_Harmful_dept
0,0,B10,서울특별시교육청,7010057,가락고등학교,Garak High School,고등학교,서울특별시,송파구,서울특별시교육청,...,일반계,NaN,후기,주간,19881223,19890428,20230115,37.501076,127.116426,0
1,1,B10,서울특별시교육청,7011169,가재울고등학교,Gajaeul High School,고등학교,서울특별시,서대문구,서울특별시교육청,...,일반계,NaN,후기,주간,20130301,20130501,20230115,37.574364,126.909530,0
2,2,B10,서울특별시교육청,7010117,강동고등학교,Kangdong High School,고등학교,서울특별시,강동구,서울특별시교육청,...,일반계,NaN,후기,주간,19841217,19850908,20230115,37.549917,127.160668,0
3,3,B10,서울특별시교육청,7010118,강서고등학교,Gangseo High School,고등학교,서울특별시,양천구,서울특별시교육청,...,일반계,NaN,후기,주간,19831101,19831101,20230115,37.536316,126.865771,0
4,4,B10,서울특별시교육청,7010270,강서공업고등학교,Gangseo Technical High School,고등학교,서울특별시,강서구,서울특별시교육청,...,전문계,NaN,전기,주간,19940105,19940105,20230115,37.576034,126.816182,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,315,B10,서울특별시교육청,7010766,효문고등학교,Hyomun High School,고등학교,서울특별시,도봉구,서울특별시교육청,...,일반계,NaN,후기,주간,20051229,20060605,20230115,37.652699,127.018400,0
316,316,B10,서울특별시교육청,7010292,휘경공업고등학교,Hwigyeong Technical High School,고등학교,서울특별시,동대문구,서울특별시교육청,...,전문계,NaN,전기,주간,19971220,19980702,20230115,37.585153,127.069451,0
317,317,B10,서울특별시교육청,7010267,휘경여자고등학교,Hwikyung Girls` High School,고등학교,서울특별시,동대문구,서울특별시교육청,...,일반계,NaN,후기,주간,19750303,19750519,20230115,37.581901,127.067434,1
318,318,B10,서울특별시교육청,7010268,휘문고등학교,Whimoon High School,고등학교,서울특별시,강남구,서울특별시교육청,...,일반계,NaN,전기,주간,19060501,19060501,20230115,37.505289,127.061994,0
319,319,B10,서울특별시교육청,7011113,휘봉고등학교,HWIBONG High School,고등학교,서울특별시,동대문구,서울특별시교육청,...,일반계,NaN,후기,주간,20120106,20120501,20230115,37.586372,127.068941,0

In [10]:
school_loc_data.to_csv('/Users/hyeoxx/Desktop/혁준/shj/DATAexam/융복합/청소년유해업소.csv', index=False, encoding='utf-8-sig')

0     178
1      52
2      28
3      16
4      12
6       6
5       4
7       4
8       3
11      3
19      3
9       2
10      2
12      2
20      1
16      1
15      1
14      1
22      1
Name: 500m_inner_Harmful_dept, dtype: int64